const vscode = require('vscode');

const messages = {
  'en': {
    'noBuildCommand': 'No build command configured.',
    'addCommand': 'Add Command',
    'buildComplete': 'Build task completed',
    'buildFailed': 'Build task failed: {0}',
    'downloadComplete': 'Download completed',
    'downloadFailed': 'Download failed, exit code: {0}',
    'downloadError': 'Download failed: {0}',
    'downloadTimeout': 'Download timeout',
    'downloadStartFailed': 'Failed to start download process: {0}',
    'noFirmware': 'No valid firmware found, please specify file/directory',
    'firmwareNotFound': 'Firmware not found, please specify firmware path',
    'copyPathFailed': 'Failed to copy path: {0}',
    'toolNotFound': 'Download tool not found: {0}!!!',
    'enterDownloadMode': 'Please enter download mode',
    'previousProcessTerminated': 'Previous process terminated',
    'previousProcessTerminateFailed': 'Previous process terminate failed: {0}',
    'childProcessTerminated': 'Child process terminated',
    'childProcessTerminateFailed': 'Child process terminate failed: {0}',
    'selectFirmwareDir': 'Select firmware directory',
    'confirmFirmwareDir': 'Firmware directory:\\n{0} ?',
    'yes': 'Yes',
    'no': 'No',
    'copyPath': 'Copy Path',
    'clickToDownload': 'Click to download',
    'deviceInfo': 'Device Info',
    'noDeviceFound': 'No device found',
    'checkDeviceConnection': 'Please check device connection',
    'current': 'Current: {0}',
    'clickToSwitch': 'Click to switch build command',
    'noBuildCommandConfigured': 'No build command configured. Click to add.',
    'building': 'Building: {0}',
    'waitingForDownload': 'Waiting for download',
    'downloadSuccess': 'Download success',
    'downloadFailed2': 'Download failed',
    'startFailed': 'Start failed',
    'downloadException': 'Download exception',
    'commandNameEmpty': 'Command name cannot be empty',
    'commandNameExists': 'Command name already exists',
    'commandEmpty': 'Command cannot be empty',
    'commandAdded': 'Build command "{0}" added successfully',
    'selectActiveCommand': 'Selected "{0}" as active build command',
    'switchedTo': 'Switched to "{0}"',
    'addNewCommand': 'Add New Build Command',
    'configureNewCommand': 'Configure a new build command',
    'selectCommandToSwitch': 'Select build command to switch',
    'autoDetectedSaved': 'Auto-detected build command saved: {0}',
    'alreadyDownloading': 'Already downloading task, ignore this request!',
    'zipCheckFailed': 'ZIP file check failed: {0}',
    'enterCommandName': 'Enter command name',
    'enterBuildCommand': 'Enter build command',
    'enterBuildCommandPlaceholder': 'e.g., build.bat new EC200ACN_DA EC200ACNDAR01A01M16',
    'configGitBashPath': 'Please configure git bash.exe path',
    'rootBuildFile': 'Root build file name: {0}',
    'gitBashPath': 'git bash.exe path: {0}',
    'currentWorkspace': 'Current workspace folder: {0}',
    'configUri': 'Config uri: {0}',
    'selectedUri': 'Selected uri: {0}',
    'lastDlState': 'Last dl state: {0}',
    'doLastDlProcessKill': 'Do last dl process kill',
    'previousProcessTerminateSuccess': 'Previous process terminate success',
    'doChildDownloadProcessKill': 'Do child download process kill.',
    'childProcessTerminateSuccess': 'Child process terminated.',
    'adProgress': 'ad progress:{0}',
    'parsingJsonError': 'Error parsing JSON: {0}',
    'configurationWritten': 'Configuration written to: {0}',
    'failedToWriteConfig': 'Failed to write firmware-cli.json: {0}',
    'command.build': 'Build Firmware',
    'command.download': 'Download Firmware',
    'view.pluginSettings': 'Plugin Settings',
    'view.showWelcome': 'Show Welcome',
    'view.extensionTools': 'Extension Tools',
    'view.search': 'Search',
    'view.logViewer': 'Log Viewer',
    'confirmBuildCommand': 'Current build command:\n{0}\n\nExecute build?',
    'executeBuild': 'Yes',
    'switchCommand': 'Switch',
    'addScriptFromFile': 'Add Script from File',
    'selectScriptFile': 'Select Script File',
    'scriptFileAdded': 'Script command "{0}" added',
    'scriptFileSelected': 'Script file selected. Review and click Add to save.',
    // Welcome and Wizard
    'welcome.title': 'Welcome - Quick Firmware +',
    'welcome.header': 'Welcome to Quick Firmware +',
    'welcome.subtitle': 'A tool for building and syncing firmware in a developer-friendly way',
    'welcome.feature.download': 'Firmware Download',
    'welcome.feature.download.desc': 'Support multiple firmware formats including FBF, PAC, ZIP, and more',
    'welcome.feature.build': 'Build Integration',
    'welcome.feature.build.desc': 'Quickly build firmware with customizable build commands',
    'welcome.feature.device': 'Device Management',
    'welcome.feature.device.desc': 'Monitor connected devices and manage firmware downloads',
    'welcome.feature.extensionTools': 'Extension Tools',
    'welcome.feature.extensionTools.desc': 'Powerful tools including Log Viewer and File Search for enhanced productivity',
    'welcome.startWizard': 'Start Setup Wizard',
    'welcome.openSettings': 'Open Settings',
    'welcome.close': 'Close',
    'welcome.shortcuts': 'Keyboard Shortcuts',
    'welcome.footer': 'Need help? Check the documentation or report issues on GitHub.',
    'welcome.dontShowAgain': 'Don\'t show this again',
    'wizard.title': 'Setup Wizard',
    'wizard.subtitle': 'Configure Quick Firmware + for your workspace',
    'wizard.firmwarePath': 'Firmware Path',
    'wizard.firmwarePath.placeholder': 'Select firmware directory...',
    'wizard.browse': 'Browse...',
    'wizard.buildCommands': 'Build Commands',
    'wizard.commandName': 'Name',
    'wizard.commandValue': 'Command',
    'wizard.addCommand': 'Add Command',
    'wizard.gitBashPath': 'Git Bash Path (Optional)',
    'wizard.gitBashPath.placeholder': 'Select git-bash.exe...',
    'wizard.gitBashPath.optional': 'Required only when using .sh build scripts on Windows',
    'wizard.prev': 'Previous',
    'wizard.next': 'Next',
    'wizard.finish': 'Finish',
    'wizard.cancel': 'Cancel',
    'wizard.notSet': 'Not set',
    'wizard.configSaved': 'Configuration saved successfully!',
    'workspaceWizardPrompt': 'This workspace appears to be a firmware project. Would you like to run the setup wizard?',
    'selectGitBash': 'Select Git Bash',
    // Wizard enhancements
    'wizard.detectedPaths': 'Detected Paths',
    'wizard.searchingPaths': 'Searching for firmware paths...',
    'wizard.autoDetected': 'Auto',
    'wizard.configured': 'Config',
    'wizard.selectScriptFile': 'Select from Script File',
    'wizard.addManualCommand': 'Add Manual Command',
    'wizard.or': 'or',
    'wizard.noCommandsAdded': 'No build commands added yet. Use the buttons above to add commands.',
    // Settings page
    'settings.title': 'Plugin Settings',
    'settings.subtitle': 'Manage your firmware tool configuration',
    'settings.firmwarePath': 'Firmware Path',
    'settings.firmwarePathLabel': 'Firmware Directory',
    'settings.firmwarePathDesc': 'Path to the directory containing firmware files',
    'settings.firmwarePathPlaceholder': 'Select firmware directory...',
    'settings.buildCommands': 'Build Commands',
    'settings.buildCommandsLabel': 'Build Command List',
    'settings.buildCommandsDesc': 'Configure build scripts for your project',
    'settings.commandName': 'Name',
    'settings.commandValue': 'Command',
    'settings.commandActions': 'Actions',
    'settings.noCommands': 'No build commands configured',
    'settings.addCommand': 'Add Build Command',
    'settings.commandNamePlaceholder': 'e.g., Release Build',
    'settings.commandValuePlaceholder': 'e.g., build.bat',
    'settings.add': 'Add',
    'settings.gitBashPath': 'Git Bash Path',
    'settings.gitBashPathLabel': 'Git Bash Executable',
    'settings.gitBashPathDesc': 'Path to git-bash.exe for running shell scripts (optional)',
    'settings.gitBashPathPlaceholder': 'C:\\Program Files\\Git\\git-bash.exe',
    'settings.comPort': 'COM Port',
    'settings.comPortLabel': 'Default COM Port',
    'settings.comPortDesc': 'Default serial port for device communication (optional)',
    'settings.comPortPlaceholder': 'e.g., COM3',
    'settings.language': 'Language',
    'settings.languageLabel': 'Display Language',
    'settings.languageDesc': 'Select your preferred language',
    'settings.languageAuto': 'Auto (follow VS Code)',
    'settings.languageZhCn': 'Chinese (Simplified)',
    'settings.languageEn': 'English',
    'settings.configFile': 'Configuration File',
    'settings.configFileLabel': 'firmware-cli.json',
    'settings.configFileDesc': 'Configuration is stored in this file in your workspace',
    'settings.configFileLoading': 'Loading...',
    'settings.openConfigFile': 'Open in Editor',
    'settings.reset': 'Reset to Defaults',
    'settings.save': 'Save Settings',
    'settings.saved': 'Settings saved successfully',
    'settings.saveFailed': 'Failed to save settings',
    'settings.resetSuccess': 'Settings reset to defaults',
    'settings.resetFailed': 'Failed to reset settings',
    'settings.configFileNotFound': 'Configuration file not found',
    // Theme settings
    'settings.theme': 'Theme',
    'settings.themeLabel': 'Display Theme',
    'settings.themeDesc': 'Select your preferred color theme',
    'settings.themeAuto': 'Auto (follow VS Code)',
    'settings.themeDark': 'Dark',
    'settings.themeLight': 'Light',
    // Search panel
    'search.title': 'File Search',
    'search.placeholder': 'Type to search files...',
    'search.emptyTitle': 'Start searching',
    'search.emptyDescription': 'Global search classification UI based on Everything',
    'search.scopeLabel': 'Search Scope',
    'search.scopeGlobal': 'Global',
    'search.scopeWorkspace': 'Workspace',
    'search.maxResultsLabel': 'Max Results',
    'search.revealInExplorer': 'Reveal in Explorer',
    'search.addToFavorites': 'Add to Favorites',
    'search.copyPath': 'Copy Path',
    'search.noResults': 'No results found for "{0}"',
    'search.resultsFound': 'Found {0} results for "{1}"',
    'search.error': 'Search error: {0}',
    // Log Viewer
    'logviewer.title': 'Log Viewer',
    'logviewer.search': 'Search',
    'logviewer.filter': 'Filter',
    'logviewer.markbook': 'Markbook',
    'logviewer.tools': 'Tools',
    'logviewer.searchPlaceholder': 'Search keyword (supports regex)...',
    'logviewer.filterPlaceholder': 'Filter pattern (regex)...',
    'logviewer.noResults': 'No results found',
    'logviewer.resultsCount': '{0} results found',
    'logviewer.caseSensitive': 'Case Sensitive',
    'logviewer.wholeWord': 'Whole Word',
    'logviewer.useRegex': 'Use Regex',
    'logviewer.prevMatch': 'Previous Match',
    'logviewer.nextMatch': 'Next Match',
    'logviewer.clearSearch': 'Clear Search',
    'logviewer.applyFilter': 'Apply Filter',
    'logviewer.clearFilter': 'Clear Filter',
    'logviewer.addToMarkbook': 'Add to Markbook',
    'logviewer.removeFromMarkbook': 'Remove from Markbook',
    'logviewer.clearMarkbook': 'Clear Markbook',
    'logviewer.jumpToLine': 'Jump to Line',
    'logviewer.syncWithOriginal': 'Sync with Original',
    'logviewer.highlightColor': 'Highlight Color',
    'logviewer.highlightAll': 'Highlight All Matches',
    'logviewer.clearHighlight': 'Clear Highlight',
    'logviewer.hexToStr': 'HEX to String',
    'logviewer.strToHex': 'String to HEX',
    'logviewer.hexConverter': 'HEX Converter',
    'logviewer.programmerCalc': 'Programmer Calculator',
    'logviewer.inputHex': 'Input HEX',
    'logviewer.inputDec': 'Input DEC',
    'logviewer.inputOct': 'Input OCT',
    'logviewer.inputBin': 'Input BIN',
    'logviewer.line': 'Line',
    'logviewer.content': 'Content',
    'logviewer.noFile': 'No log file opened',
    'logviewer.loading': 'Loading...',
    'logviewer.loadError': 'Failed to load file: {0}',
    'logviewer.fileTooLarge': 'File too large, showing first {0} lines',
    'logviewer.noMarkbookItems': 'No bookmarks added',
    'logviewer.bookmarkAdded': 'Bookmark added at line {0}',
    'logviewer.bookmarkRemoved': 'Bookmark removed',
    'logviewer.filterApplied': 'Filter applied: {0} results',
    'logviewer.filterCleared': 'Filter cleared',
    'logviewer.searchCompleted': 'Search completed: {0} matches',
    'logviewer.encoding': 'Encoding',
    'logviewer.encodingAuto': 'Auto Detect',
    'logviewer.encodingUtf8': 'UTF-8',
    'logviewer.encodingGbk': 'GBK',
    'logviewer.encodingLatin1': 'Latin-1'
  },
  'zh-cn': {
    'noBuildCommand': '没有配置构建命令。',
    'addCommand': '添加命令',
    'buildComplete': '构建任务完成',
    'buildFailed': '构建任务失败: {0}',
    'downloadComplete': '下载完成',
    'downloadFailed': '下载失败，退出码: {0}',
    'downloadError': '下载失败: {0}',
    'downloadTimeout': '下载等待超时',
    'downloadStartFailed': '启动下载进程失败: {0}',
    'noFirmware': '无法识别到有效下载固件，请指定文件/目录',
    'firmwareNotFound': '未找到固件，请指定固件路径',
    'copyPathFailed': '复制路径失败: {0}',
    'toolNotFound': '未找到下载工具: {0}!!!',
    'enterDownloadMode': '请进入下载模式',
    'previousProcessTerminated': '前一个进程已终止',
    'previousProcessTerminateFailed': '前一个进程终止失败: {0}',
    'childProcessTerminated': '子进程已终止',
    'childProcessTerminateFailed': '子进程终止失败: {0}',
    'selectFirmwareDir': '选择固件目录',
    'confirmFirmwareDir': '固件目录:\\n{0} ?',
    'yes': '是',
    'no': '否',
    'copyPath': '复制路径',
    'clickToDownload': '点击下载',
    'deviceInfo': '设备信息',
    'noDeviceFound': '未找到设备',
    'checkDeviceConnection': '请检查设备连接',
    'current': '当前: {0}',
    'clickToSwitch': '点击切换构建命令',
    'noBuildCommandConfigured': '没有配置构建命令。点击添加。',
    'building': '正在构建: {0}',
    'waitingForDownload': '等待下载',
    'downloadSuccess': '下载成功',
    'downloadFailed2': '下载失败',
    'startFailed': '启动失败',
    'downloadException': '下载异常',
    'commandNameEmpty': '命令名称不能为空',
    'commandNameExists': '命令名称已存在',
    'commandEmpty': '命令不能为空',
    'commandAdded': '构建命令 "{0}" 添加成功',
    'selectActiveCommand': '已选择 "{0}" 作为活动构建命令',
    'switchedTo': '已切换到 "{0}"',
    'addNewCommand': '添加新构建命令',
    'configureNewCommand': '配置新构建命令',
    'selectCommandToSwitch': '选择要切换的构建命令',
    'autoDetectedSaved': '自动检测的构建命令已保存: {0}',
    'alreadyDownloading': '已有下载任务正在进行，忽略此请求!',
    'zipCheckFailed': 'ZIP文件检查失败: {0}',
    'enterCommandName': '输入命令名称',
    'enterBuildCommand': '输入构建命令',
    'enterBuildCommandPlaceholder': '例如: build.bat new EC200ACN_DA EC200ACNDAR01A01M16',
    'configGitBashPath': '请配置git bash.exe路径',
    'rootBuildFile': '根构建文件名: {0}',
    'gitBashPath': 'git bash.exe 路径: {0}',
    'currentWorkspace': '当前工作区文件夹: {0}',
    'configUri': '配置uri: {0}',
    'selectedUri': '选中uri: {0}',
    'lastDlState': '上次下载状态: {0}',
    'doLastDlProcessKill': '执行上次下载进程终止',
    'previousProcessTerminateSuccess': '前一个进程终止成功',
    'doChildDownloadProcessKill': '执行子下载进程终止。',
    'childProcessTerminateSuccess': '子进程已终止。',
    'adProgress': 'ad 进度:{0}',
    'parsingJsonError': '解析JSON错误: {0}',
    'configurationWritten': '配置已写入: {0}',
    'failedToWriteConfig': '写入 firmware-cli.json 失败: {0}',
    'command.build': '编译固件',
    'command.download': '固件下载',
    'view.pluginSettings': '插件设置',
    'view.showWelcome': '显示欢迎页',
    'view.extensionTools': '扩展工具',
    'view.search': '本地搜索',
    'view.logViewer': '日志分析',
    'confirmBuildCommand': '当前构建命令:\n{0}\n\n执行编译?',
    'executeBuild': '是',
    'switchCommand': '切换',
    'addScriptFromFile': '从选择脚本添加',
    'selectScriptFile': '选择脚本文件',
    'scriptFileAdded': '脚本命令 "{0}" 已添加',
    'scriptFileSelected': 'Script file selected. Review and click Add to save.',
    // Welcome and Wizard
    'welcome.title': '欢迎 - Quick Firmware +',
    'welcome.header': '欢迎使用 Quick Firmware +',
    'welcome.subtitle': '一个开发者友好的编译下载和工具箱的合集UI',
    'welcome.feature.download': '固件下载',
    'welcome.feature.download.desc': '支持多平台固件快捷下载，可自行配置期望平台下载的UI',
    'welcome.feature.build': '编译集成',
    'welcome.feature.build.desc': '使用可自定义的构建命令图标快速编译固件',
    'welcome.feature.device': '设备管理',
    'welcome.feature.device.desc': '监控已连接设备列表',
    'welcome.feature.extensionTools': '扩展工具',
    'welcome.feature.extensionTools.desc': '强大的日志查看器和文件搜索工具，提升开发效率',
    'welcome.startWizard': '设置向导',
    'welcome.openSettings': '打开设置',
    'welcome.close': '关闭',
    'welcome.shortcuts': '键盘快捷键',
    'welcome.footer': '需要帮助？请查看文档或在 GitHub 上报告问题。',
    'welcome.dontShowAgain': '不再显示',
    'wizard.title': '设置向导',
    'wizard.subtitle': '为您的工程空间配置 Quick Firmware +',
    'wizard.firmwarePath': '固件路径',
    'wizard.firmwarePath.placeholder': '选择固件目录...',
    'wizard.browse': '浏览...',
    'wizard.buildCommands': '构建命令',
    'wizard.commandName': '名称',
    'wizard.commandValue': '命令',
    'wizard.addCommand': '添加命令',
    'wizard.gitBashPath': 'Git Bash 路径（可选）',
    'wizard.gitBashPath.placeholder': '选择 git-bash.exe...',
    'wizard.gitBashPath.optional': '仅在 Windows 上使用 .sh 构建脚本时需要',
    'wizard.prev': '上一步',
    'wizard.next': '下一步',
    'wizard.finish': '完成',
    'wizard.cancel': '取消',
    'wizard.notSet': '未设置',
    'wizard.configSaved': '配置保存成功！',
    'workspaceWizardPrompt': '此工作空间看起来是一个固件项目。是否运行设置向导？',
    'selectGitBash': '选择 Git Bash',
    // Wizard enhancements
    'wizard.detectedPaths': '检测到的路径',
    'wizard.searchingPaths': '正在搜索固件路径...',
    'wizard.autoDetected': '自动',
    'wizard.configured': '配置',
    'wizard.selectScriptFile': '从脚本文件选择',
    'wizard.addManualCommand': '手动添加命令',
    'wizard.or': '或',
    'wizard.noCommandsAdded': '尚未添加构建命令。使用上方按钮添加命令。',
    // Settings page
    'settings.title': '插件设置',
    'settings.subtitle': '管理您的固件工具配置',
    'settings.firmwarePath': '固件路径',
    'settings.firmwarePathLabel': '固件目录',
    'settings.firmwarePathDesc': '包含固件文件的目录路径',
    'settings.firmwarePathPlaceholder': '选择固件目录...',
    'settings.buildCommands': '构建命令',
    'settings.buildCommandsLabel': '构建命令列表',
    'settings.buildCommandsDesc': '为您的项目配置构建脚本',
    'settings.commandName': '名称',
    'settings.commandValue': '命令',
    'settings.commandActions': '操作',
    'settings.noCommands': '未配置构建命令',
    'settings.addCommand': '添加构建命令',
    'settings.commandNamePlaceholder': '例如: Release Build',
    'settings.commandValuePlaceholder': '例如: build.bat',
    'settings.add': '添加',
    'settings.gitBashPath': 'Git Bash 路径',
    'settings.gitBashPathLabel': 'Git Bash 可执行文件',
    'settings.gitBashPathDesc': '用于运行 shell 脚本的 git-bash.exe 路径（可选）',
    'settings.gitBashPathPlaceholder': 'C:\\Program Files\\Git\\git-bash.exe',
    'settings.comPort': '串口',
    'settings.comPortLabel': '默认串口',
    'settings.comPortDesc': '设备通信的默认串口（可选）',
    'settings.comPortPlaceholder': '例如: COM3',
    'settings.language': '语言',
    'settings.languageLabel': '显示语言',
    'settings.languageDesc': '选择您偏好的语言',
    'settings.languageAuto': '自动（跟随 VS Code）',
    'settings.languageZhCn': '简体中文',
    'settings.languageEn': '英文',
    'settings.configFile': '配置文件',
    'settings.configFileLabel': 'firmware-cli.json',
    'settings.configFileDesc': '配置存储在工作区的此文件中',
    'settings.configFileLoading': '加载中...',
    'settings.openConfigFile': '在编辑器中打开',
    'settings.reset': '重置为默认值',
    'settings.save': '保存设置',
    'settings.saved': '设置保存成功',
    'settings.saveFailed': '设置保存失败',
    'settings.resetSuccess': '设置已重置为默认值',
    'settings.resetFailed': '设置重置失败',
    'settings.configFileNotFound': '未找到配置文件',
    // Theme settings
    'settings.theme': '主题',
    'settings.themeLabel': '显示主题',
    'settings.themeDesc': '选择您偏好的颜色主题',
    'settings.themeAuto': '自动（跟随 VS Code）',
    'settings.themeDark': '暗色',
    'settings.themeLight': '浅色',
    // Search panel
    'search.title': '文件搜索',
    'search.placeholder': '输入关键词搜索文件...',
    'search.emptyTitle': '开始搜索',
    'search.emptyDescription': '基于everything的PC全局搜索分类UI',
    'search.scopeLabel': '搜索范围',
    'search.scopeGlobal': '全局',
    'search.scopeWorkspace': '工作区',
    'search.maxResultsLabel': '最大结果数',
    'search.revealInExplorer': '在资源管理器中显示',
    'search.addToFavorites': '添加到收藏',
    'search.copyPath': '复制路径',
    'search.noResults': '未找到 "{0}" 的搜索结果',
    'search.resultsFound': '找到 {0} 个 "{1}" 的搜索结果',
    'search.error': '搜索错误: {0}',
    // Log Viewer
    'logviewer.title': '日志查看器',
    'logviewer.search': '搜索',
    'logviewer.filter': '过滤',
    'logviewer.markbook': '书签',
    'logviewer.tools': '工具',
    'logviewer.searchPlaceholder': '搜索关键词（支持正则）...',
    'logviewer.filterPlaceholder': '过滤模式（正则）...',
    'logviewer.noResults': '未找到结果',
    'logviewer.resultsCount': '找到 {0} 个结果',
    'logviewer.caseSensitive': '区分大小写',
    'logviewer.wholeWord': '全字匹配',
    'logviewer.useRegex': '使用正则',
    'logviewer.prevMatch': '上一个匹配',
    'logviewer.nextMatch': '下一个匹配',
    'logviewer.clearSearch': '清除搜索',
    'logviewer.applyFilter': '应用过滤',
    'logviewer.clearFilter': '清除过滤',
    'logviewer.addToMarkbook': '添加到书签',
    'logviewer.removeFromMarkbook': '从书签移除',
    'logviewer.clearMarkbook': '清除书签',
    'logviewer.jumpToLine': '跳转到行',
    'logviewer.syncWithOriginal': '同步到原始位置',
    'logviewer.highlightColor': '高亮颜色',
    'logviewer.highlightAll': '高亮所有匹配',
    'logviewer.clearHighlight': '清除高亮',
    'logviewer.hexToStr': 'HEX 转字符串',
    'logviewer.strToHex': '字符串转 HEX',
    'logviewer.hexConverter': 'HEX 转换器',
    'logviewer.programmerCalc': '程序员计算器',
    'logviewer.inputHex': '输入 HEX',
    'logviewer.inputDec': '输入 DEC',
    'logviewer.inputOct': '输入 OCT',
    'logviewer.inputBin': '输入 BIN',
    'logviewer.line': '行号',
    'logviewer.content': '内容',
    'logviewer.noFile': '未打开日志文件',
    'logviewer.loading': '加载中...',
    'logviewer.loadError': '加载文件失败: {0}',
    'logviewer.fileTooLarge': '文件过大，显示前 {0} 行',
    'logviewer.noMarkbookItems': '未添加书签',
    'logviewer.bookmarkAdded': '已在第 {0} 行添加书签',
    'logviewer.bookmarkRemoved': '书签已移除',
    'logviewer.filterApplied': '过滤已应用: {0} 个结果',
    'logviewer.filterCleared': '过滤已清除',
    'logviewer.searchCompleted': '搜索完成: {0} 个匹配',
    'logviewer.encoding': '编码',
    'logviewer.encodingAuto': '自动检测',
    'logviewer.encodingUtf8': 'UTF-8',
    'logviewer.encodingGbk': 'GBK',
    'logviewer.encodingLatin1': 'Latin-1'
  }
};

function getLocale() {
  const config = vscode.workspace.getConfiguration('quickFirmwarePlus');
  const language = config.get('language', 'auto');
  
  if (language === 'auto') {
    return vscode.env.language.toLowerCase();
  }
  return language.toLowerCase();
}

function localize(key, ...args) {
  const locale = getLocale();
  const lang = messages[locale] || messages['en'];
  let message = lang[key] || messages['en'][key] || key;
  
  // Replace placeholders {0}, {1}, etc.
  args.forEach((arg, index) => {
    message = message.replace(`{${index}}`, arg);
  });
  
  return message;
}

module.exports = { localize };
