const vscode = require('vscode');
const { configManager } = require('./config/configManager');

const messages = {
  'en': {
    'noBuildCommand': 'No build command configured.',
    'addCommand': 'Add Command',
    'buildComplete': 'Build task completed',
    'buildFailed': 'Build task failed: {0}',
    'downloadComplete': 'Download completed',
    'downloadFailed': 'Download failed, exit code: {0}',
    'downloadError': 'Download failed: {0}',
    'downloadTimeout': 'Download timeout',
    'downloadStartFailed': 'Failed to start download process: {0}',
    'noFirmware': 'No valid firmware found, please specify file/directory',
    'firmwareNotFound': 'Firmware not found, please specify firmware path',
    'copyPathFailed': 'Failed to copy path: {0}',
    'toolNotFound': 'Download tool not found: {0}!!!',
    'enterDownloadMode': 'Please enter download mode',
    'previousProcessTerminated': 'Previous process terminated',
    'previousProcessTerminateFailed': 'Previous process terminate failed: {0}',
    'childProcessTerminated': 'Child process terminated',
    'childProcessTerminateFailed': 'Child process terminate failed: {0}',
    'selectFirmwareDir': 'Select firmware directory',
    'confirmFirmwareDir': 'Firmware directory:\\n{0} ?',
    'yes': 'Yes',
    'no': 'No',
    'copyPath': 'Copy Path',
    'clickToDownload': 'Click to download',
    'deviceInfo': 'Device Info',
    'noDeviceFound': 'No device found',
    'checkDeviceConnection': 'Please check device connection',
    'current': 'Current: {0}',
    'clickToSwitch': 'Click to switch build command',
    'noBuildCommandConfigured': 'No build command configured. Click to add.',
    'building': 'Building: {0}',
    'waitingForDownload': 'Waiting for download',
    'downloadSuccess': 'Download success',
    'downloadFailed2': 'Download failed',
    'startFailed': 'Start failed',
    'downloadException': 'Download exception',
    'commandNameEmpty': 'Command name cannot be empty',
    'commandNameExists': 'Command name already exists',
    'commandEmpty': 'Command cannot be empty',
    'commandAdded': 'Build command "{0}" added successfully',
    'selectActiveCommand': 'Selected "{0}" as active build command',
    'switchedTo': 'Switched to "{0}"',
    'addNewCommand': 'Add New Build Command',
    'configureNewCommand': 'Configure a new build command',
    'selectCommandToSwitch': 'Select build command to switch',
    'autoDetectedSaved': 'Auto-detected build command saved: {0}',
    'alreadyDownloading': 'Already downloading task, ignore this request!',
    'zipCheckFailed': 'ZIP file check failed: {0}',
    'enterCommandName': 'Enter command name',
    'enterBuildCommand': 'Enter build command',
    'enterBuildCommandPlaceholder': 'e.g., build.bat new EC200ACN_DA EC200ACNDAR01A01M16',
    'configGitBashPath': 'Please configure git bash.exe path',
    'rootBuildFile': 'Root build file name: {0}',
    'gitBashPath': 'git bash.exe path: {0}',
    'currentWorkspace': 'Current workspace folder: {0}',
    'configUri': 'Config uri: {0}',
    'selectedUri': 'Selected uri: {0}',
    'lastDlState': 'Last dl state: {0}',
    'doLastDlProcessKill': 'Do last dl process kill',
    'previousProcessTerminateSuccess': 'Previous process terminate success',
    'doChildDownloadProcessKill': 'Do child download process kill.',
    'childProcessTerminateSuccess': 'Child process terminated.',
    'adProgress': 'ad progress:{0}',
    'parsingJsonError': 'Error parsing JSON: {0}',
    'configurationWritten': 'Configuration written to: {0}',
    'failedToWriteConfig': 'Failed to write dove.json: {0}',
    'command.build': 'Build Firmware',
    'command.download': 'Download Firmware',
    'view.pluginSettings': 'Plugin Settings',
    'view.showWelcome': 'Show Welcome',
    'view.portableTools': 'Portable Tools',
    'view.search': 'Search',
    'view.logViewer': 'Log Viewer',
    'confirmBuildCommand': 'Current build command:\n{0}\n\nExecute build?',
    'executeBuild': 'Yes',
    'switchCommand': 'Switch',
    'addScriptFromFile': 'Add Script from File',
    'selectScriptFile': 'Select Script File',
    'scriptFileAdded': 'Script command "{0}" added',
    'scriptFileSelected': 'Script file selected. Review and click Add to save.',
    // Welcome and Wizard
    'welcome.title': 'Welcome - Quick Dove',
    'welcome.header': 'Welcome to Quick Dove',
    'welcome.subtitle': 'A tool for building and syncing firmware in a developer-friendly way',
    'welcome.feature.download': 'Firmware Download',
    'welcome.feature.download.desc': 'Support multiple firmware formats including FBF, PAC, ZIP, and more',
    'welcome.feature.build': 'Build Integration',
    'welcome.feature.build.desc': 'Quickly build firmware with customizable build commands',
    'welcome.feature.device': 'Device Management',
    'welcome.feature.device.desc': 'Monitor connected devices and manage firmware downloads',
    'welcome.feature.portableTools': 'Portable Tools',
    'welcome.feature.portableTools.desc': 'Powerful tools including Log Viewer and File Search for enhanced productivity',
    'welcome.startWizard': 'Start Setup Wizard',
    'welcome.openSettings': 'Open Settings',
    'welcome.close': 'Close',
    'welcome.shortcuts': 'Keyboard Shortcuts',
    'welcome.footer': 'Need help? Check the documentation or report issues on GitHub.',
    'welcome.dontShowAgain': 'Don\'t show this again',
    'wizard.title': 'Setup Wizard',
    'wizard.subtitle': 'Configure Quick Dove for your workspace',
    'wizard.firmwarePath': 'Firmware Path',
    'wizard.firmwarePath.placeholder': 'Select firmware directory...',
    'wizard.browse': 'Browse...',
    'wizard.buildCommands': 'Build Commands',
    'wizard.commandName': 'Name',
    'wizard.commandValue': 'Command',
    'wizard.addCommand': 'Add Command',
    'wizard.gitBashPath': 'Git Bash Path (Optional)',
    'wizard.gitBashPath.placeholder': 'Select git-bash.exe...',
    'wizard.gitBashPath.optional': 'Required only when using .sh build scripts on Windows',
    'wizard.prev': 'Previous',
    'wizard.next': 'Next',
    'wizard.finish': 'Finish',
    'wizard.cancel': 'Cancel',
    'wizard.notSet': 'Not set',
    'wizard.configSaved': 'Configuration saved successfully!',
    'workspaceWizardPrompt': 'This workspace appears to be a firmware project. Would you like to run the setup wizard?',
    'selectGitBash': 'Select Git Bash',
    // Wizard enhancements
    'wizard.detectedPaths': 'Detected Paths',
    'wizard.searchingPaths': 'Searching for firmware paths...',
    'wizard.autoDetected': 'Auto',
    'wizard.configured': 'Config',
    'wizard.selectScriptFile': 'Select from Script File',
    'wizard.addManualCommand': 'Add Manual Command',
    'wizard.or': 'or',
    'wizard.noCommandsAdded': 'No build commands added yet. Use the buttons above to add commands.',
    // Settings page
    'settings.title': 'Plugin Settings',
    'settings.subtitle': 'Manage your firmware tool configuration',
    'settings.firmwarePath': 'Firmware Path',
    'settings.firmwarePathLabel': 'Firmware Directory',
    'settings.firmwarePathDesc': 'Path to the directory containing firmware files',
    'settings.firmwarePathPlaceholder': 'Select firmware directory...',
    'settings.buildCommands': 'Build Commands',
    'settings.buildCommandsLabel': 'Build Command List',
    'settings.buildCommandsDesc': 'Configure build scripts for your project',
    'settings.commandName': 'Name',
    'settings.commandValue': 'Command',
    'settings.commandActions': 'Actions',
    'settings.noCommands': 'No build commands configured',
    'settings.addCommand': 'Add Build Command',
    'settings.commandNamePlaceholder': 'e.g., Release Build',
    'settings.commandValuePlaceholder': 'e.g., build.bat',
    'settings.add': 'Add',
    'settings.gitBashPath': 'Git Bash Path',
    'settings.gitBashPathLabel': 'Git Bash Executable',
    'settings.gitBashPathDesc': 'Path to git-bash.exe for running shell scripts (optional)',
    'settings.gitBashPathPlaceholder': 'C:\\Program Files\\Git\\git-bash.exe',
    'settings.comPort': 'COM Port',
    'settings.comPortLabel': 'Default COM Port',
    'settings.comPortDesc': 'Default serial port for device communication (optional)',
    'settings.comPortPlaceholder': 'e.g., COM3',
    // COM Ports (multi-port with tags)
    'settings.comPorts': 'COM Ports',
    'settings.comPortsLabel': 'Serial Port Configuration',
    'settings.comPortsDesc': 'Configure serial ports with tags for AI automation. AI can use --tag parameter to auto-select the appropriate port.',
    'settings.portName': 'Port',
    'settings.portTags': 'Tag',
    'settings.portActions': 'Actions',
    'settings.noPorts': 'No ports configured',
    'settings.addPort': 'Add Port',
    'settings.editPort': 'Edit Port',
    'settings.portNamePlaceholder': 'e.g., COM3',
    'settings.portExists': 'Port already exists',
    'settings.portNameEmpty': 'Please enter port name',
    'settings.portTagEmpty': 'Please select a tag',
    'settings.selectTag': 'Select Tag',
    'settings.scanPorts': 'Scan Ports',
    'settings.noPortsFound': 'No serial ports found',
    'settings.availablePorts': 'Available Ports',
    'settings.deletePortConfirm': 'Delete port "{0}"?',
    'settings.delete': 'Delete',
    // New PortTag types (synced with dove submodule)
    'settings.tagUARTAT': 'UART_AT',
    'settings.tagUARTDBG': 'UART_DBG',
    'settings.tagUSBAT': 'USB_AT',
    'settings.tagUSBDIAG': 'USB_DIAG',
    'settings.tagInvalid': 'Invalid',
    'settings.tagUARTATDesc': 'UART port for AT commands (dove port at --tag UART_AT)',
    'settings.tagUARTDBGDesc': 'UART port for debug logs (dove port monitor --tag UART_DBG)',
    'settings.tagUSBATDesc': 'USB virtual port for AT commands',
    'settings.tagUSBDIAGDesc': 'USB virtual port for diagnostics',
    'settings.tagInvalidDesc': 'Port is unusable, AI should not use',
    'settings.language': 'Language',
    'settings.languageLabel': 'Display Language',
    'settings.languageDesc': 'Select your preferred language',
    'settings.languageAuto': 'Auto (follow VS Code)',
    'settings.languageZhCn': 'Chinese (Simplified)',
    'settings.languageEn': 'English',
    'settings.configFile': 'Configuration File',
    'settings.configFileLabel': 'dove.json',
    'settings.configFileDesc': 'Configuration is stored in this file in your workspace',
    'settings.configFileLoading': 'Loading...',
    'settings.openConfigFile': 'Open in Editor',
    'settings.reset': 'Reset to Defaults',
    'settings.resetShort': 'Reset',
    'settings.resetConfirm': 'Are you sure you want to reset all settings to defaults?',
    'settings.save': 'Save Settings',
    'settings.saveShort': 'Save',
    'settings.saved': 'Settings saved successfully',
    'settings.saveFailed': 'Failed to save settings',
    'settings.resetSuccess': 'Settings reset to defaults',
    'settings.agentIntegration': 'Agent Integration',
    'settings.skillIntegration': 'Skill Integration',
    'settings.skillIntegrationDesc': 'Import SKILL files to AI Agent so AI can use dove tools',
    'settings.installToClaudeCode': 'Install to Claude Code',
    'settings.installToCline': 'Install to Cline',
    'settings.installing': 'Installing...',
    'settings.installSuccess': 'Installation successful',
    'settings.installFailed': 'Installation failed',
    'settings.resetFailed': 'Failed to reset settings',
    'settings.configFileNotFound': 'Configuration file not found',
    // Installation status
    'settings.installStatus': 'Installation Status',
    'settings.checkStatus': 'Check Status',
    'settings.checkingStatus': 'Checking...',
    'settings.installed': 'Installed',
    'settings.notInstalled': 'Not Installed',
    'settings.install': 'Install',
    'settings.uninstall': 'Uninstall',
    'settings.uninstalling': 'Uninstalling...',
    'settings.uninstallSuccess': 'Uninstallation successful',
    'settings.uninstallFailed': 'Uninstallation failed',
    'settings.oldVersionFound': 'Old version found, will be replaced during installation',
    'settings.version': 'Version',
    'settings.extensionName': 'Extension',
    // Theme settings
    'settings.theme': 'Theme',
    'settings.themeLabel': 'Display Theme',
    'settings.themeDesc': 'Select your preferred color theme',
    'settings.themeAuto': 'Auto (follow VS Code)',
    'settings.themeDark': 'Dark',
    'settings.themeLight': 'Light',
    'settings.accentColorLabel': 'Accent Color',
    'settings.accentColorDesc': 'Choose the accent color for the UI theme',
    'settings.accentCyan': 'Cyan',
    'settings.accentBlue': 'Blue',
    'settings.accentGreen': 'Green',
    'settings.accentMagenta': 'Magenta',
    'settings.accentYellow': 'Yellow',
    'settings.accentRed': 'Red',
    'settings.accentWhite': 'White',
    // Search panel
    'search.title': 'File Search',
    'search.placeholder': 'Type to search files...',
    'search.emptyTitle': 'Start searching',
    'search.emptyDescription': 'Everything global search categorization, please configure the http connection on first use.',
    'search.scopeLabel': 'Search Scope',
    'search.scopeGlobal': 'Global',
    'search.scopeWorkspace': 'Workspace',
    'search.maxResultsLabel': 'Max Results',
    'search.revealInExplorer': 'Reveal in Explorer',
    'search.addToFavorites': 'Add to Favorites',
    'search.copyPath': 'Copy Path',
    'search.noResults': 'No results found for "{0}"',
    'search.resultsFound': 'Found {0} results for "{1}"',
    'search.error': 'Search error: {0}',
    // Log Viewer
    'logviewer.title': 'Log Viewer',
    'logviewer.search': 'Search',
    'logviewer.filter': 'Filter',
    'logviewer.markbook': 'Markbook',
    'logviewer.tools': 'Tools',
    'logviewer.searchPlaceholder': 'Search keyword (supports regex)...',
    'logviewer.filterPlaceholder': 'Filter pattern (regex)...',
    'logviewer.noResults': 'No results found',
    'logviewer.resultsCount': '{0} results found',
    'logviewer.caseSensitive': 'Case Sensitive',
    'logviewer.wholeWord': 'Whole Word',
    'logviewer.useRegex': 'Use Regex',
    'logviewer.prevMatch': 'Previous Match',
    'logviewer.nextMatch': 'Next Match',
    'logviewer.clearSearch': 'Clear Search',
    'logviewer.applyFilter': 'Apply Filter',
    'logviewer.clearFilter': 'Clear Filter',
    'logviewer.addToMarkbook': 'Add to Markbook',
    'logviewer.removeFromMarkbook': 'Remove from Markbook',
    'logviewer.clearMarkbook': 'Clear Markbook',
    'logviewer.jumpToLine': 'Jump to Line',
    'logviewer.syncWithOriginal': 'Sync with Original',
    'logviewer.highlightColor': 'Highlight Color',
    'logviewer.highlightAll': 'Highlight All Matches',
    'logviewer.clearHighlight': 'Clear Highlight',
    'logviewer.hexToStr': 'HEX to String',
    'logviewer.strToHex': 'String to HEX',
    'logviewer.hexConverter': 'HEX Converter',
    'logviewer.programmerCalc': 'Programmer Calculator',
    'logviewer.inputHex': 'Input HEX',
    'logviewer.inputDec': 'Input DEC',
    'logviewer.inputOct': 'Input OCT',
    'logviewer.inputBin': 'Input BIN',
    'logviewer.line': 'Line',
    'logviewer.content': 'Content',
    'logviewer.noFile': 'No log file opened',
    'logviewer.loading': 'Loading...',
    'logviewer.loadError': 'Failed to load file: {0}',
    'logviewer.fileTooLarge': 'File too large, showing first {0} lines',
    'logviewer.noMarkbookItems': 'No bookmarks added',
    'logviewer.bookmarkAdded': 'Bookmark added at line {0}',
    'logviewer.bookmarkRemoved': 'Bookmark removed',
    'logviewer.filterApplied': 'Filter applied: {0} results',
    'logviewer.filterCleared': 'Filter cleared',
    'logviewer.searchCompleted': 'Search completed: {0} matches',
    'logviewer.encoding': 'Encoding',
    'logviewer.encodingAuto': 'Auto Detect',
    'logviewer.encodingUtf8': 'UTF-8',
    'logviewer.encodingGbk': 'GBK',
    'logviewer.encodingLatin1': 'Latin-1',
    'logviewer.emptyDesc': 'Open a log file to view and analyze its content',
    'logviewer.selectFile': 'Select Log File',
    'logviewer.supportedFormats': 'Supported formats: .log, .txt, .out, .err',
    'logviewer.recentFiles': 'Recent Files',
    'logviewer.fileNotFound': 'File not found or inaccessible',
    'logviewer.copyPath': 'Copy Path',
    // C/C++ Define Helper
    'settings.cppDefine': 'C/C++ Define Helper',
    'settings.cppDefineLabel': 'Preprocessor Defines',
    'settings.cppDefineDesc': 'Manage C/C++ IntelliSense preprocessor defines',
    'settings.cppDefineList': 'Current Defines',
    'settings.cppDefineAdd': 'Add Define',
    'settings.cppDefineDelete': 'Delete',
    'settings.cppDefineEmpty': 'No defines configured',
    'settings.cppDefinePlaceholder': 'e.g., DEBUG_MODE',
    'settings.cppDefineKeybinding': 'Shortcut Key',
    'settings.cppDefineKeybindingDesc': 'Press Ctrl+D (Cmd+D on Mac) in editor to toggle selected text as define',
    'settings.cppDefineOpenKeybinding': 'Open Keybinding Settings',
    'cppDefineAdded': 'Define added: {0}',
    'cppDefineRemoved': 'Define removed: {0}',
    'cppDefineInvalid': 'Invalid define name (must be uppercase letters, numbers, underscores)',
    'cppDefineNoSelection': 'No text selected',
    'cppDefineNoWorkspace': 'No workspace folder found'
  },
  'zh-cn': {
    'noBuildCommand': '没有配置构建命令。',
    'addCommand': '添加命令',
    'buildComplete': '构建任务完成',
    'buildFailed': '构建任务失败: {0}',
    'downloadComplete': '下载完成',
    'downloadFailed': '下载失败，退出码: {0}',
    'downloadError': '下载失败: {0}',
    'downloadTimeout': '下载等待超时',
    'downloadStartFailed': '启动下载进程失败: {0}',
    'noFirmware': '无法识别到有效下载固件，请指定文件/目录',
    'firmwareNotFound': '未找到固件，请指定固件路径',
    'copyPathFailed': '复制路径失败: {0}',
    'toolNotFound': '未找到下载工具: {0}!!!',
    'enterDownloadMode': '请进入下载模式',
    'previousProcessTerminated': '前一个进程已终止',
    'previousProcessTerminateFailed': '前一个进程终止失败: {0}',
    'childProcessTerminated': '子进程已终止',
    'childProcessTerminateFailed': '子进程终止失败: {0}',
    'selectFirmwareDir': '选择固件目录',
    'confirmFirmwareDir': '固件目录:\\n{0} ?',
    'yes': '是',
    'no': '否',
    'copyPath': '复制路径',
    'clickToDownload': '点击下载',
    'deviceInfo': '设备信息',
    'noDeviceFound': '未找到设备',
    'checkDeviceConnection': '请检查设备连接',
    'current': '当前: {0}',
    'clickToSwitch': '点击切换构建命令',
    'noBuildCommandConfigured': '没有配置构建命令。点击添加。',
    'building': '正在构建: {0}',
    'waitingForDownload': '等待下载',
    'downloadSuccess': '下载成功',
    'downloadFailed2': '下载失败',
    'startFailed': '启动失败',
    'downloadException': '下载异常',
    'commandNameEmpty': '命令名称不能为空',
    'commandNameExists': '命令名称已存在',
    'commandEmpty': '命令不能为空',
    'commandAdded': '构建命令 "{0}" 添加成功',
    'selectActiveCommand': '已选择 "{0}" 作为活动构建命令',
    'switchedTo': '已切换到 "{0}"',
    'addNewCommand': '添加新构建命令',
    'configureNewCommand': '配置新构建命令',
    'selectCommandToSwitch': '选择要切换的构建命令',
    'autoDetectedSaved': '自动检测的构建命令已保存: {0}',
    'alreadyDownloading': '已有下载任务正在进行，忽略此请求!',
    'zipCheckFailed': 'ZIP文件检查失败: {0}',
    'enterCommandName': '输入命令名称',
    'enterBuildCommand': '输入构建命令',
    'enterBuildCommandPlaceholder': '例如: build.bat new EC200ACN_DA EC200ACNDAR01A01M16',
    'configGitBashPath': '请配置git bash.exe路径',
    'rootBuildFile': '根构建文件名: {0}',
    'gitBashPath': 'git bash.exe 路径: {0}',
    'currentWorkspace': '当前工作区文件夹: {0}',
    'configUri': '配置uri: {0}',
    'selectedUri': '选中uri: {0}',
    'lastDlState': '上次下载状态: {0}',
    'doLastDlProcessKill': '执行上次下载进程终止',
    'previousProcessTerminateSuccess': '前一个进程终止成功',
    'doChildDownloadProcessKill': '执行子下载进程终止。',
    'childProcessTerminateSuccess': '子进程已终止。',
    'adProgress': 'ad 进度:{0}',
    'parsingJsonError': '解析JSON错误: {0}',
    'configurationWritten': '配置已写入: {0}',
    'failedToWriteConfig': '写入 dove.json 失败: {0}',
    'command.build': '编译固件',
    'command.download': '固件下载',
    'view.pluginSettings': '设置',
    'view.showWelcome': '欢迎页',
    'view.portableTools': '便携工具',
    'view.search': '本地搜索',
    'view.logViewer': '日志分析',
    'confirmBuildCommand': '当前构建命令:\n{0}\n\n执行编译?',
    'executeBuild': '是',
    'switchCommand': '切换',
    'addScriptFromFile': '选择脚本添加',
    'selectScriptFile': '脚本选择',
    'scriptFileAdded': '脚本命令 "{0}" 已添加',
    'scriptFileSelected': 'Script file selected. Review and click Add to save.',
    // Welcome and Wizard
    'welcome.title': '欢迎 - Quick Dove',
    'welcome.header': '欢迎使用 Quick Dove',
    'welcome.subtitle': '一个开发者友好的编译下载和工具箱的合集UI',
    'welcome.feature.download': '固件下载',
    'welcome.feature.download.desc': '支持多平台固件快捷下载，可自行配置期望平台下载的UI',
    'welcome.feature.build': '编译集成',
    'welcome.feature.build.desc': '使用可自定义的构建命令图标快速编译固件',
    'welcome.feature.device': '设备管理',
    'welcome.feature.device.desc': '监控已连接设备列表',
    'welcome.feature.portableTools': '便携工具',
    'welcome.feature.portableTools.desc': '强大的日志查看器和文件搜索工具，提升开发效率',
    'welcome.startWizard': '设置向导',
    'welcome.openSettings': '打开设置',
    'welcome.close': '关闭',
    'welcome.shortcuts': '键盘快捷键',
    'welcome.footer': '需要帮助？请查看文档或在 GitHub 上报告问题。',
    'welcome.dontShowAgain': '不再显示',
    'wizard.title': '设置向导',
    'wizard.subtitle': '为您的工程空间配置 Quick Dove',
    'wizard.firmwarePath': '固件路径',
    'wizard.firmwarePath.placeholder': '选择固件目录...',
    'wizard.browse': '浏览...',
    'wizard.buildCommands': '构建命令',
    'wizard.commandName': '名称',
    'wizard.commandValue': '命令',
    'wizard.addCommand': '添加命令',
    'wizard.gitBashPath': 'Git Bash 路径（可选）',
    'wizard.gitBashPath.placeholder': '选择 git-bash.exe...',
    'wizard.gitBashPath.optional': '仅在 Windows 上使用 .sh 构建脚本时需要',
    'wizard.prev': '上一步',
    'wizard.next': '下一步',
    'wizard.finish': '完成',
    'wizard.cancel': '取消',
    'wizard.notSet': '未设置',
    'wizard.configSaved': '配置保存成功！',
    'workspaceWizardPrompt': '此工作空间看起来是一个固件项目。是否运行设置向导？',
    'selectGitBash': '选择 Git Bash',
    // Wizard enhancements
    'wizard.detectedPaths': '检测到的路径',
    'wizard.searchingPaths': '正在搜索固件路径...',
    'wizard.autoDetected': '自动',
    'wizard.configured': '配置',
    'wizard.selectScriptFile': '从脚本文件选择',
    'wizard.addManualCommand': '手动添加命令',
    'wizard.or': '或',
    'wizard.noCommandsAdded': '尚未添加构建命令。使用上方按钮添加命令。',
    // Settings page
    'settings.title': '设置',
    'settings.subtitle': '管理您的固件工具配置',
    'settings.firmwarePath': '固件路径',
    'settings.firmwarePathLabel': '固件目录',
    'settings.firmwarePathDesc': '包含固件文件的目录路径',
    'settings.firmwarePathPlaceholder': '选择固件目录...',
    'settings.buildCommands': '构建命令',
    'settings.buildCommandsLabel': '构建命令列表',
    'settings.buildCommandsDesc': '为您的项目配置构建脚本',
    'settings.commandName': '名称',
    'settings.commandValue': '命令',
    'settings.commandActions': '操作',
    'settings.noCommands': '未配置构建命令',
    'settings.addCommand': '添加构建命令',
    'settings.commandNamePlaceholder': '例如: Release Build',
    'settings.commandValuePlaceholder': '例如: build.bat',
    'settings.add': '添加',
    'settings.gitBashPath': 'Git Bash 路径',
    'settings.gitBashPathLabel': 'Git Bash 可执行文件',
    'settings.gitBashPathDesc': '用于运行 shell 脚本的 git-bash.exe 路径（可选）',
    'settings.gitBashPathPlaceholder': 'C:\\Program Files\\Git\\git-bash.exe',
    'settings.comPort': '串口',
    'settings.comPortLabel': '默认串口',
    'settings.comPortDesc': '设备通信的默认串口（可选）',
    'settings.comPortPlaceholder': '例如: COM3',
    // COM Ports (多端口标签配置)
    'settings.comPorts': '串口配置',
    'settings.comPortsLabel': '串口列表配置',
    'settings.comPortsDesc': '为串口添加标签，帮助 AI 自动选择合适端口。AI 可使用 --tag 参数自动选择对应端口。',
    'settings.portName': '端口',
    'settings.portTags': '标签',
    'settings.portActions': '操作',
    'settings.noPorts': '未配置端口',
    'settings.addPort': '添加端口',
    'settings.editPort': '编辑端口',
    'settings.portNamePlaceholder': '例如: COM3',
    'settings.portExists': '端口已存在',
    'settings.portNameEmpty': '请输入端口名称',
    'settings.portTagEmpty': '请选择标签',
    'settings.selectTag': '选择标签',
    'settings.scanPorts': '扫描端口',
    'settings.noPortsFound': '未找到串口',
    'settings.availablePorts': '可用端口',
    'settings.deletePortConfirm': '删除端口 "{0}"?',
    'settings.delete': '删除',
    // New PortTag types (synced with dove submodule)
    'settings.tagUARTAT': 'UART_AT',
    'settings.tagUARTDBG': 'UART_DBG',
    'settings.tagUSBAT': 'USB_AT',
    'settings.tagUSBDIAG': 'USB_DIAG',
    'settings.tagInvalid': '无效',
    'settings.tagUARTATDesc': 'UART AT命令端口 (dove port at --tag UART_AT)',
    'settings.tagUARTDBGDesc': 'UART 调试日志端口 (dove port monitor --tag UART_DBG)',
    'settings.tagUSBATDesc': 'USB虚拟AT命令端口',
    'settings.tagUSBDIAGDesc': 'USB虚拟诊断端口',
    'settings.tagInvalidDesc': '端口不可用，AI不应使用',
    'settings.language': '语言',
    'settings.languageLabel': '显示语言',
    'settings.languageDesc': '选择您偏好的语言',
    'settings.languageAuto': '自动（跟随 VS Code）',
    'settings.languageZhCn': '简体中文',
    'settings.languageEn': '英文',
    'settings.configFile': '配置文件',
    'settings.configFileLabel': 'dove.json',
    'settings.configFileDesc': '配置存储在工作区的此文件中',
    'settings.configFileLoading': '加载中...',
    'settings.openConfigFile': '在编辑器中打开',
    'settings.reset': '重置为默认值',
    'settings.resetShort': '重置',
    'settings.resetConfirm': '确定要将所有设置重置为默认值吗？',
    'settings.save': '保存设置',
    'settings.saveShort': '保存',
    'settings.saved': '设置保存成功',
    'settings.saveFailed': '设置保存失败',
    'settings.resetSuccess': '设置已重置为默认值',
    'settings.agentIntegration': 'Agent 集成',
    'settings.skillIntegration': 'Skill 集成',
    'settings.skillIntegrationDesc': '将SKILL文件导入到 AI Agent，让 AI 可以调用dove工具',
    'settings.installToClaudeCode': '安装到 Claude Code',
    'settings.installToCline': '安装到 Cline',
    'settings.installing': '正在安装...',
    'settings.installSuccess': '安装成功',
    'settings.installFailed': '安装失败',
    'settings.resetFailed': '设置重置失败',
    'settings.configFileNotFound': '未找到配置文件',
    // Installation status
    'settings.installStatus': '安装状态',
    'settings.checkStatus': '检查状态',
    'settings.checkingStatus': '正在检查...',
    'settings.installed': '已安装',
    'settings.notInstalled': '未安装',
    'settings.install': '安装',
    'settings.uninstall': '卸载',
    'settings.uninstalling': '正在卸载...',
    'settings.uninstallSuccess': '卸载成功',
    'settings.uninstallFailed': '卸载失败',
    'settings.oldVersionFound': '发现旧版本，安装时将自动替换',
    'settings.version': '版本',
    'settings.extensionName': '扩展',
    // Theme settings
    'settings.theme': '主题',
    'settings.themeLabel': '显示主题',
    'settings.themeDesc': '选择您偏好的颜色主题',
    'settings.themeAuto': '自动（跟随 VS Code）',
    'settings.themeDark': '暗色',
    'settings.themeLight': '浅色',
    'settings.accentColorLabel': '主题色',
    'settings.accentColorDesc': '选择界面主题的强调色',
    'settings.accentCyan': '青色',
    'settings.accentBlue': '蓝色',
    'settings.accentGreen': '绿色',
    'settings.accentMagenta': '紫红色',
    'settings.accentYellow': '黄色',
    'settings.accentRed': '红色',
    'settings.accentWhite': '白色',
    // Search panel
    'search.title': '文件搜索',
    'search.placeholder': '输入关键词搜索文件...',
    'search.emptyTitle': '开始搜索',
    'search.emptyDescription': '基于everything的全局搜索分类，首次使用请先设置连接HTTP服务',
    'search.scopeLabel': '搜索范围',
    'search.scopeGlobal': '全局',
    'search.scopeWorkspace': '工作区',
    'search.maxResultsLabel': '最大结果数',
    'search.revealInExplorer': '在资源管理器中显示',
    'search.addToFavorites': '添加到收藏',
    'search.copyPath': '复制路径',
    'search.noResults': '未找到 "{0}" 的搜索结果',
    'search.resultsFound': '找到 {0} 个 "{1}" 的搜索结果',
    'search.error': '搜索错误: {0}',
    // Log Viewer
    'logviewer.title': '日志查看器',
    'logviewer.search': '搜索',
    'logviewer.filter': '过滤',
    'logviewer.markbook': '书签',
    'logviewer.tools': '工具',
    'logviewer.searchPlaceholder': '搜索关键词（支持正则）...',
    'logviewer.filterPlaceholder': '过滤模式（正则）...',
    'logviewer.noResults': '未找到结果',
    'logviewer.resultsCount': '找到 {0} 个结果',
    'logviewer.caseSensitive': '区分大小写',
    'logviewer.wholeWord': '全字匹配',
    'logviewer.useRegex': '使用正则',
    'logviewer.prevMatch': '上一个匹配',
    'logviewer.nextMatch': '下一个匹配',
    'logviewer.clearSearch': '清除搜索',
    'logviewer.applyFilter': '应用过滤',
    'logviewer.clearFilter': '清除过滤',
    'logviewer.addToMarkbook': '添加到书签',
    'logviewer.removeFromMarkbook': '从书签移除',
    'logviewer.clearMarkbook': '清除书签',
    'logviewer.jumpToLine': '跳转到行',
    'logviewer.syncWithOriginal': '同步到原始位置',
    'logviewer.highlightColor': '高亮颜色',
    'logviewer.highlightAll': '高亮所有匹配',
    'logviewer.clearHighlight': '清除高亮',
    'logviewer.hexToStr': 'HEX 转字符串',
    'logviewer.strToHex': '字符串转 HEX',
    'logviewer.hexConverter': 'HEX 转换器',
    'logviewer.programmerCalc': '程序员计算器',
    'logviewer.inputHex': '输入 HEX',
    'logviewer.inputDec': '输入 DEC',
    'logviewer.inputOct': '输入 OCT',
    'logviewer.inputBin': '输入 BIN',
    'logviewer.line': '行号',
    'logviewer.content': '内容',
    'logviewer.noFile': '未打开日志文件',
    'logviewer.loading': '加载中...',
    'logviewer.loadError': '加载文件失败: {0}',
    'logviewer.fileTooLarge': '文件过大，显示前 {0} 行',
    'logviewer.noMarkbookItems': '未添加书签',
    'logviewer.bookmarkAdded': '已在第 {0} 行添加书签',
    'logviewer.bookmarkRemoved': '书签已移除',
    'logviewer.filterApplied': '过滤已应用: {0} 个结果',
    'logviewer.filterCleared': '过滤已清除',
    'logviewer.searchCompleted': '搜索完成: {0} 个匹配',
    'logviewer.encoding': '编码',
    'logviewer.encodingAuto': '自动检测',
    'logviewer.encodingUtf8': 'UTF-8',
    'logviewer.encodingGbk': 'GBK',
    'logviewer.encodingLatin1': 'Latin-1',
    'logviewer.emptyDesc': '打开日志文件以查看和分析其内容',
    'logviewer.selectFile': '选择日志文件',
    'logviewer.supportedFormats': '过滤分层、高亮关键词、笔记本，载入识别格式: .log, .txt, .out, .err',
    'logviewer.recentFiles': '最近文件',
    'logviewer.fileNotFound': '文件未找到或无法访问',
    'logviewer.copyPath': '复制路径',
    // C/C++ Define Helper
    'settings.cppDefine': 'C/C++ 宏辅助',
    'settings.cppDefineLabel': '预处理器宏定义',
    'settings.cppDefineDesc': '管理 C/C++ IntelliSense 预处理器宏定义',
    'settings.cppDefineList': '当前手动协助分析宏定义列表',
    'settings.cppDefineAdd': '添加宏定义',
    'settings.cppDefineDelete': '删除',
    'settings.cppDefineEmpty': '未配置宏定义',
    'settings.cppDefinePlaceholder': '例如: DEBUG_MODE',
    'settings.cppDefineKeybinding': '快捷键',
    'settings.cppDefineKeybindingDesc': '在编辑器中选中文本后按 Ctrl+D（Mac: Cmd+D）可快速切换宏定义',
    'settings.cppDefineOpenKeybinding': '打开快捷键设置',
    'cppDefineAdded': '已添加宏定义: {0}',
    'cppDefineRemoved': '已删除宏定义: {0}',
    'cppDefineInvalid': '无效的宏定义名称（必须为大写字母、数字、下划线）',
    'cppDefineNoSelection': '未选中文本',
    'cppDefineNoWorkspace': '未找到工作区文件夹'
  }
};

function getLocale() {
  // Read language from dove.json (configManager) instead of VS Code settings
  const language = configManager.getLanguage();

  if (language === 'auto') {
    return vscode.env.language.toLowerCase();
  }
  return language.toLowerCase();
}

function localize(key, ...args) {
  const locale = getLocale();
  const lang = messages[locale] || messages['en'];
  let message = lang[key] || messages['en'][key] || key;
  
  // Replace placeholders {0}, {1}, etc.
  args.forEach((arg, index) => {
    message = message.replace(`{${index}}`, arg);
  });
  
  return message;
}

module.exports = { localize };
